[package]
edition = "2021"
name    = "affine_native"
version = "0.0.0"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
noop = ["napi/noop", "napi-derive/noop"]

[[bench]]
name    = "hashcash"
harness = false

[dependencies]
affine_common = { workspace = true }
affine_schema = { path = "./schema" }
anyhow        = { workspace = true }
chrono        = { workspace = true }
criterion2    = { workspace = true }
napi          = { workspace = true }
napi-derive   = { workspace = true }
notify        = { workspace = true, features = ["serde"] }
once_cell     = { workspace = true }
parking_lot   = { workspace = true }
rand          = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
sha3          = { workspace = true }
sqlx          = { workspace = true, default-features = false, features = ["chrono", "macros", "migrate", "runtime-tokio", "sqlite", "tls-rustls"] }
tokio         = { workspace = true, features = ["full"] }
uuid          = { workspace = true, features = ["fast-rng", "serde", "v4"] }

[dev-dependencies]
rayon = { workspace = true }

[build-dependencies]
affine_schema = { path = "./schema" }
dotenv        = { workspace = true }
napi-build    = { workspace = true }
sqlx          = { workspace = true, default-features = false, features = ["chrono", "json", "macros", "migrate", "runtime-tokio", "sqlite", "tls-rustls"] }
tokio         = { workspace = true, features = ["full"] }
